# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-09 23:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edecan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='edecanes')),
                ('alineacion', models.CharField(choices=[('top', 'Arriba'), ('center', 'Centrado'), ('bottom', 'Abajo')], default='center', max_length=6)),
                ('prioridad', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Edecanes',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('recipient', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('nattachments', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 18, 44, 16, 742153), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='eventos')),
                ('lugar', models.CharField(blank=True, max_length=60, null=True)),
                ('servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('posicion', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 18, 44, 16, 741822), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='sliders')),
                ('titulo', models.CharField(blank=True, max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=45)),
                ('posicion', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.TextField()),
                ('autor', models.CharField(blank=True, max_length=60)),
                ('puesto', models.CharField(blank=True, max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Testimoniales',
            },
        ),
    ]
